Auto-detecting location of bakefile.m4 in bootstrap script instead of hard-coding it.
git-svn-id: svn://svn.gna.org/svn/mysqlpp/trunk@2035 5946f024-35f4-0310-b1b3-9a3be3380cfb

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -56,8 +56,24 @@ if [ -n "$success" ]
 then
 	mv autoconf_inc.m4 config > /dev/null 2>&1	# don't care if it fails
 
+	# Find location of Bakefile's stock M4 autoconf macros
+	for d in /usr /usr/local
+	do
+		BAKEFILE_M4=$d/share/aclocal
+		if [ -e $BAKEFILE_M4/bakefile.m4 ] ; then break ; fi
+	done
+	if [ ! -e $BAKEFILE_M4/bakefile.m4 ]
+	then
+		echo
+		echo "Failed to find bakefile.m4.  Add the directory containing"
+		echo "this to the bootstrap script."
+		echo
+		exit 1
+	fi
+
 	success=
-	aclocal -I config -I /usr/local/share/aclocal &&
+	set -x &&
+		aclocal -I config -I $BAKEFILE_M4 &&
 		autoheader &&
 		autoconf &&
 		./configure --cache-file=config.cache --enable-maintainer-mode $* &&
